### ISSUE TITLE
force blur not working as in screenshot

### ISSUE THREAD

**Issue by FantasyPvP** [taj-ny/kwin-forceblur#18]
added vscodium and systemsettings to the window classes to force blur as shown in the screenshot, however neither of these windows were blurred. is there a specific theme or colourscheme I need to install? 
I'm using Lightly with a transparent colourscheme already

![image](https://github.com/taj-ny/kwin-forceblur/assets/80643031/8d2a7545-484d-4034-b113-aa6c1f8f527f)

EDIT: info i should probably add 

Operating System: Arch Linux 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8350U CPU @ 1.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by taj-ny** [comment]
I set the window opacity to 85% in the screenshots.

**Comment by FantasyPvP** [comment]
> I set the window opacity to 85% in the screenshots.

thanks, Is that done through plasma settings?

**Comment by taj-ny** [comment]
Yes, right click on the titlebar -> More Actions -> Configure Special Window/Application Settings, or System Settings -> Window Management -> Window Rules

**Comment by FantasyPvP** [comment]
> Yes, right click on the titlebar -> More Actions -> Configure Special Window/Application Settings, or System Settings -> Window Management -> Window Rules

tysm, closing the issue.

**Comment by taj-ny** [comment]
> EDIT: might also be a good idea to clarify this in the readme so people don't open more issues in the future asking why the blur doesn't work
I will.

> EDIT 2: setting the opacity of systemsettings to 85% barely makes a difference, I have to get it to around 50% before it really affects anything
That's why I don't use a dark wallpaper.

**Comment by FantasyPvP** [comment]
> That's why I don't use a dark wallpaper.

I was using the same wallpaper as in the screenshot in the readme when I tried changing the opacity. not sure it's worth trying to get transparency working on settings anyway though, the settings app really doesn't seem to respect system theming at all, imo it needs a UI rewrite
