### ISSUE TITLE
validating source files with sha256sums failed

### ISSUE THREAD

**Issue by FantasyPvP** [taj-ny/kwin-forceblur#19]
I was able to successfully install this on my laptop, however when trying it on my desktop I get this issue.
(the package still build fine when directly git cloning and installing from source)

![image](https://github.com/taj-ny/kwin-forceblur/assets/80643031/a3586b65-2163-49cf-9bb2-a1f3862fad0f)

is anyone else having this issue?

**Comment by D3SOX** [comment]
Sorry my bad fixed now
